server:
  port: 8765

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka


spring:
  application:
    name: hr-api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
  config:
    import: optional:configserver


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
         


#spring:
#  main:
#    web-application-type: reactive
#  cloud:
#    gateway:
#      routes:
#
#        - id: hr-payroll
#          uri: lb://hr-payroll
#          predicates:
#            - Path=/payments/**
#
#        - id: hr-worker
#          uri: lb://hr-worker
#          predicates:
#            - Path=/workers/**
#            
#  application:
#      name: hr-api-gateway
#     
   
  
     

    
   
      
    

    
    
    
    
    