spring:
  application:
    name: hr-oauth

    
#------#
    
eureka:

  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
      
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


#-----#
    
server:
  port: ${PORT:0}
