spring:

  application:
    name: hr-config-server
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/matetocoti/ms-course-configs
          default-label: main
          username: ${GITHUB_USER}
          password: ${GITHUB_PASS}

server:
  port: 8888
