eureka:

  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
      
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


#-----#
    
server:
  port: ${PORT:0}


#--------#

spring:

  jpa:
   defer-datasource-initialization: true

  application:
    name: hr-user
    
  datasource:
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
    
  h2:
    console:
      enabled: true
      path: /h2-console
